### ISSUE TITLE
Windows getting very laggy after installation

### ISSUE THREAD

**Issue by Realitaetsverlust** [dev-andi/xfce-blur-effects#1]
After running the command `/usr/local/bin/xfwm4 --replace & disown`, the windows become very unresponsive and laggy. It's hard to drag them, they respond very slowly when trying to enter something, even the menubar with file, edit etc is very slow to use. If deactivate the blur effects via the Xfwm Effects Application, the behavior persists. Only after I restore the original xfwm4 via `/usr/bin/xfwm4 --replace & disown`, everything works again. I also noted it becomes significantly laggier the more windows are open. One is slightly bearable. Four means, hell no.

I have completely restarted my system after installing it, nothing changed. The system is also an extremely fresh install (I've installed it from scratch yesterday).I also have quite a beefy machine which should be able to handle it.

Not sure if there are any logfiles you need. There was nothing in the system logs I can find that was out of the ordinary, however, if you need any particular logfile, just let me know.

Neofetch:

```[realitaetsverlust@exodus ~]$ neofetch
                   -`                    realitaetsverlust@exodus 
                  .o+`                   ------------------ 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: MS-7C37 1.0 
               `+oooooo:                 Kernel: 5.15.5-arch1-1 
               -+oooooo+:                Uptime: 5 hours, 46 mins 
             `/:-:++oooo+:               Packages: 634 (pacman) 
            `/++++/+++++++:              Shell: bash 5.1.12 
           `/++++++++++++++:             Resolution: 3840x2160, 3840x2160 
          `/+++ooooooooooooo/`           DE: Xfce 4.16 
         ./ooosssso++osssssso+`          WM: Xfwm4 
        .oossssso-````/ossssss+`         WM Theme: Default 
       -osssssso.      :ssssssso.        Theme: Adwaita-dark [GTK2/3] 
      :osssssss/        osssso+++.       Icons: Adwaita [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: xfce4-terminal 
   `/ossssso+/:-        -:/+osssso+-     Terminal Font: Source Code Pro Medium 12 
  `+sso+:-`                 `.-/+oso:    CPU: AMD Ryzen 9 5900X (24) @ 3.700GHz 
 `++:.                           `-/+/   GPU: NVIDIA GeForce GTX 1080 
 .`                                 `/   GPU: AMD ATI Radeon RX 6800/6800 XT / 6900 XT 
                                         Memory: 2099MiB / 32084MiB```

**Comment by dev-andi** [comment]
Hi, I didn't see this so apologies for the delay. Must have been due to the old xfwm components. It has been updated to use XFCE4.16 . Let me know if that works. Slight delays are to be expected but not by a large margin. [Edit: as this is still experimental]
